import { Video } from '../objects/video';

export const VIDEOS: Video[] = [
	{ id: 1, 
	  title: 'Some video', 
	  filename: 'video1', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'teddy',
	  publishedOn: new Date(2017, 6, 23),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'News',
	  views: 1000000,
	},
	{ id: 2, 
	  title: 'Some cool video', 
	  filename: 'video2', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'tux',
	  publishedOn: new Date(2017, 6, 22),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'Movies',
	  views: 100000,
	},
		{ id: 3, 
	  title: 'The best video ever', 
	  filename: 'video3', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'melmo',
	  publishedOn: new Date(2017, 6, 21),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'News',
	  views: 1000000,
	},
		{ id: 4, 
	  title: 'Some video about stuff and things', 
	  filename: 'video4', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'teddy',
	  publishedOn: new Date(2016, 6, 23),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'Animals',
	  views: 123456,
	},
		{ id: 5, 
	  title: 'Some cat video', 
	  filename: 'video5', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'teddy',
	  publishedOn: new Date(2017, 5, 23),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'Animals',
	  views: 1000000,
	},
		{ id: 6, 
	  title: 'Some righteous video', 
	  filename: 'video6', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'tux',
	  publishedOn: new Date(2017, 3, 23),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'News',
	  views: 54321,
	},
		{ id: 7, 
	  title: 'Some bitchin video', 
	  filename: 'video7', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'melmo',
	  publishedOn: new Date(2017, 2, 23),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'Travel',
	  views: 76754,
	},
		{ id: 8, 
	  title: 'Some travel video', 
	  filename: 'video8', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'teddy',
	  publishedOn: new Date(2017, 1, 23),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'Travel',
	  views: 987432,
	},
		{ id: 9, 
	  title: 'Some dog video', 
	  filename: 'video9', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'tux',
	  publishedOn: new Date(2016, 3, 3),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'News',
	  views: 889032,
	},
		{ id: 10, 
	  title: 'Some news video', 
	  filename: 'video10', 
	  thumbnail: 'http://placekitten.com/110/196', 
	  username: 'teddy',
	  publishedOn: new Date(2016, 4, 20),
	  description: "This is video about a bunch of really cool stuff and things that are really cool.",
	  category: 'News',
	  views: 83455,
	}
]